// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: differenceProduct.proto

package protos

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumberFirst  int64 `protobuf:"varint,1,opt,name=numberFirst,proto3" json:"numberFirst,omitempty"`
	NumberSecond int64 `protobuf:"varint,2,opt,name=numberSecond,proto3" json:"numberSecond,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_differenceProduct_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_differenceProduct_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_differenceProduct_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetNumberFirst() int64 {
	if x != nil {
		return x.NumberFirst
	}
	return 0
}

func (x *Request) GetNumberSecond() int64 {
	if x != nil {
		return x.NumberSecond
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CalculatedAnswer int64 `protobuf:"varint,1,opt,name=calculatedAnswer,proto3" json:"calculatedAnswer,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_differenceProduct_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_differenceProduct_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_differenceProduct_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetCalculatedAnswer() int64 {
	if x != nil {
		return x.CalculatedAnswer
	}
	return 0
}

var File_differenceProduct_proto protoreflect.FileDescriptor

var file_differenceProduct_proto_rawDesc = []byte{
	0x0a, 0x17, 0x64, 0x69, 0x66, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x22, 0x4f, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x46, 0x69, 0x72, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x46, 0x69, 0x72, 0x73, 0x74, 0x12, 0x22,
	0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x22, 0x36, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a,
	0x0a, 0x10, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x32, 0x85, 0x01, 0x0a, 0x0e, 0x53,
	0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x44, 0x69, 0x76, 0x69, 0x64, 0x65, 0x12, 0x3a, 0x0a,
	0x13, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x69, 0x66, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x10, 0x43, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_differenceProduct_proto_rawDescOnce sync.Once
	file_differenceProduct_proto_rawDescData = file_differenceProduct_proto_rawDesc
)

func file_differenceProduct_proto_rawDescGZIP() []byte {
	file_differenceProduct_proto_rawDescOnce.Do(func() {
		file_differenceProduct_proto_rawDescData = protoimpl.X.CompressGZIP(file_differenceProduct_proto_rawDescData)
	})
	return file_differenceProduct_proto_rawDescData
}

var file_differenceProduct_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_differenceProduct_proto_goTypes = []interface{}{
	(*Request)(nil),  // 0: protos.Request
	(*Response)(nil), // 1: protos.Response
}
var file_differenceProduct_proto_depIdxs = []int32{
	0, // 0: protos.SubtractDivide.CalculateDifference:input_type -> protos.Request
	0, // 1: protos.SubtractDivide.CalculateProduct:input_type -> protos.Request
	1, // 2: protos.SubtractDivide.CalculateDifference:output_type -> protos.Response
	1, // 3: protos.SubtractDivide.CalculateProduct:output_type -> protos.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_differenceProduct_proto_init() }
func file_differenceProduct_proto_init() {
	if File_differenceProduct_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_differenceProduct_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_differenceProduct_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_differenceProduct_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_differenceProduct_proto_goTypes,
		DependencyIndexes: file_differenceProduct_proto_depIdxs,
		MessageInfos:      file_differenceProduct_proto_msgTypes,
	}.Build()
	File_differenceProduct_proto = out.File
	file_differenceProduct_proto_rawDesc = nil
	file_differenceProduct_proto_goTypes = nil
	file_differenceProduct_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SubtractDivideClient is the client API for SubtractDivide service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SubtractDivideClient interface {
	CalculateDifference(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	CalculateProduct(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type subtractDivideClient struct {
	cc grpc.ClientConnInterface
}

func NewSubtractDivideClient(cc grpc.ClientConnInterface) SubtractDivideClient {
	return &subtractDivideClient{cc}
}

func (c *subtractDivideClient) CalculateDifference(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protos.SubtractDivide/CalculateDifference", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subtractDivideClient) CalculateProduct(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protos.SubtractDivide/CalculateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubtractDivideServer is the server API for SubtractDivide service.
type SubtractDivideServer interface {
	CalculateDifference(context.Context, *Request) (*Response, error)
	CalculateProduct(context.Context, *Request) (*Response, error)
}

// UnimplementedSubtractDivideServer can be embedded to have forward compatible implementations.
type UnimplementedSubtractDivideServer struct {
}

func (*UnimplementedSubtractDivideServer) CalculateDifference(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateDifference not implemented")
}
func (*UnimplementedSubtractDivideServer) CalculateProduct(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateProduct not implemented")
}

func RegisterSubtractDivideServer(s *grpc.Server, srv SubtractDivideServer) {
	s.RegisterService(&_SubtractDivide_serviceDesc, srv)
}

func _SubtractDivide_CalculateDifference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubtractDivideServer).CalculateDifference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.SubtractDivide/CalculateDifference",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubtractDivideServer).CalculateDifference(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubtractDivide_CalculateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubtractDivideServer).CalculateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.SubtractDivide/CalculateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubtractDivideServer).CalculateProduct(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _SubtractDivide_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.SubtractDivide",
	HandlerType: (*SubtractDivideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateDifference",
			Handler:    _SubtractDivide_CalculateDifference_Handler,
		},
		{
			MethodName: "CalculateProduct",
			Handler:    _SubtractDivide_CalculateProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "differenceProduct.proto",
}
